(*
Example
grammar        : rule + ;
rule           : nonterminal ':' productionrule ';' ;
productionrule : production [ '|' production ] * ;
production     : term * ;
term           : element repeats ;
element        : LITERAL | IDENTIFIER | '[' productionrule ']' ;
repeats        : [ '*' | '+' ] NUMBER ? | NUMBER ? | '?' ;
*)

Comment
comment            : block_comment | line_comment ;
block_comment      : "/*" block_comment_body * "*/" ;
block_comment_body : [block_comment | character] * ;
line_comment       : "//" non_eol * ;

Whitespace
whitespace_char : '\x20' | '\x09' | '\x0a' | '\x0d' ;
whitespace      : [ whitespace_char | comment ] + ;

Tokens
simple_token : keyword | unop | binop ;
token        : simple_token | ident | literal | symbol | whitespace token ;

Literals
lit_suffix : ident;
literal    : [ string_lit | char_lit | byte_string_lit | byte_lit | num_lit |
               bool_lit ] lit_suffix ?;
